color: null
description: null
fieldLayouts:
  3c46f26c-e2f4-4a79-9b17-36d1f41a4965:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-20T13:32:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 80b3fe6d-fa96-4075-a87b-66e40195b590 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9a419c9-f371-4d75-bd1c-2a45d379fb2d
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-20T13:26:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5ec42e0c-d574-4174-b476-b0eea1e9c161
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-20T13:32:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: af09463e-3ae3-4197-bfd8-a026dd7b3230 # Rich text
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 329d1cac-8b7d-4d10-b033-4aa1b77d8d60
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-20T13:32:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c2a9c26f-00ce-4a49-bfc5-cba5d23652f3 # Accordion Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bee5d46-0de1-4203-b2ce-9aa01c43607d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30635cda-917c-4576-984e-72f87e2ff50d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-20T14:01:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 26acb532-e8a4-4e24-bd62-b79d3a7d5cd7 # Theme color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a6c1a20-e452-48b5-8df0-6d315054321b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-20T14:01:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 447f28a6-2439-4093-82cd-6125f73e4654 # Full-width section?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21cb88f2-2e42-4930-98e8-34f21abc1fd2
            userCondition: null
            warning: null
            width: 100
        name: Styling
        uid: d3178dad-69bc-4b67-a07c-47f21f61d844
        userCondition: null
handle: accordion
hasTitleField: true
icon: null
name: Accordion
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
