color: null
description: null
fieldLayouts:
  a08cf214-0640-43ab-96be-26e00e9e9e2c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-25T13:33:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 80b3fe6d-fa96-4075-a87b-66e40195b590 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c765ebe3-43e9-46c5-8598-aaa7b3cbf502
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-25T13:30:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3b7e68ad-07d5-41b8-a5a3-2234531ed2c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-25T13:33:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: af09463e-3ae3-4197-bfd8-a026dd7b3230 # Rich text
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d33d8e9-07b0-432c-ad4f-ad8536707a6d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-25T13:34:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 97b88b49-383f-4962-a6f6-668f5b27da01 # Blogs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba3ef8dd-eb2c-40f7-a160-f32f42c59c6b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-01T06:23:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a7b3e5b7-6148-4206-a92d-fd53efbd592d # Blog items limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e95c56c-4b03-4302-aae1-3bf757fbe904
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 138db975-b1bd-467d-a118-0ce6607531e8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-25T13:33:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 26acb532-e8a4-4e24-bd62-b79d3a7d5cd7 # Theme color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4267f03c-61fd-4729-b4c9-adf06b5b8e53
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-25T13:33:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 447f28a6-2439-4093-82cd-6125f73e4654 # Full-width section?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53a664d7-c911-4802-a284-dd1f6a788b1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-25T13:33:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbafe277-e6eb-4635-b326-7043b1e0f8a0 # Section header alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de832082-9d34-497a-aab8-b65bc3fbeaeb
            userCondition: null
            warning: null
            width: 100
        name: Styling
        uid: 0239f016-30ab-4db1-9cb1-970ac8af7bd1
        userCondition: null
handle: blogIndex
hasTitleField: true
icon: null
name: 'Blog Index'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
