color: null
description: null
fieldLayouts:
  fb2e5a85-a197-4f35-a3b7-38ab44cec6f4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-23T08:01:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 80b3fe6d-fa96-4075-a87b-66e40195b590 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5008571-9658-4212-8b65-90d9f2fe0fbb
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-23T07:58:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 27952d5b-3977-4431-9c44-0798d86664a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T08:01:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: af09463e-3ae3-4197-bfd8-a026dd7b3230 # Rich text
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cfaf96c-c2cb-4689-8b0c-501839224702
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T08:07:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 971611db-49bb-4f54-a030-a8f4cafaa6b6 # Products
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf47e0e7-3ce1-4ad7-93dd-31612ab60d0c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d834602-6204-4af0-b50f-3d2f2c9d5bf3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-23T08:01:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 26acb532-e8a4-4e24-bd62-b79d3a7d5cd7 # Theme color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f154ef48-d849-4b3c-ae00-143bd1310c2b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T14:14:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 447f28a6-2439-4093-82cd-6125f73e4654 # Full-width section?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd965f99-3834-4a32-a073-97ed63c5baf2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-23T08:01:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbafe277-e6eb-4635-b326-7043b1e0f8a0 # Section header alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 812af3ed-a228-4bc9-bf4c-3654ffabe413
            userCondition: null
            warning: null
            width: 100
        name: Styling
        uid: d2209243-f423-4c71-9a50-26372a10f9ed
        userCondition: null
handle: products
hasTitleField: true
icon: null
name: Products
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
