color: null
description: null
fieldLayouts:
  277cf601-0777-4640-b512-f174429872c3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-08T16:17:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: da072638-09ce-471a-95f3-e2d9499f3b90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40352672-1ac7-46f9-b5a6-8601c7b05cc5
        userCondition: null
handle: sitemap
hasTitleField: true
icon: null
name: Sitemap
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
