color: null
description: null
fieldLayouts:
  e747fc45-6c33-41f4-8702-d1afc9054cfb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-21T08:11:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 26acb532-e8a4-4e24-bd62-b79d3a7d5cd7 # Theme color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a61d1a3-70d3-4d2d-a937-ca4e394b2c84
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-25T10:09:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbafe277-e6eb-4635-b326-7043b1e0f8a0 # Section header alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8176c2a-b5c9-4e6c-905e-3c2a00ad4dd4
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-21T07:36:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 66751f7b-a320-418f-bac9-5872e60bf5d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-21T08:11:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: af09463e-3ae3-4197-bfd8-a026dd7b3230 # Rich text
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1423fc3-8eca-439c-bf0f-6f74ca78c645
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-21T08:11:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 282e9005-dbc2-492c-ab72-d44ef796c4b3 # Testimonials
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89262f2a-5bac-4eea-b15f-2c45b926874b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62e580f2-e403-46e6-a3c7-ee90d4170964
        userCondition: null
handle: testimonials
hasTitleField: true
icon: null
name: Testimonials
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
