baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: nl-NL
name: 'CopyThat Creations'
primary: true
siteGroup: 3198be24-dc1d-4dd1-b50f-b1e529bedeaa # CopyThat Creations
sortOrder: 1
