altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  97288450-9950-4f6e-a141-e68af364d9f0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-21T08:06:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 410ba984-11d0-4677-83f0-181061523166
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ed9ee6fa-302f-4862-9487-9747cf3967e7
        userCondition: null
fs: local
handle: testimonials
name: Testimonials
sortOrder: 4
subpath: testimonials
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
