altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  69711bda-15f8-4c42-abc2-05363e85e151:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-26T08:16:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6696a69a-5286-4dc5-adc1-376a991be149
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c98194bf-3988-4d8c-8947-5e173020174f
        userCondition: null
fs: local
handle: users
name: Users
sortOrder: 5
subpath: users
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
