columnSuffix: null
handle: ctaUrl
instructions: null
name: 'CTA URL'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:bcb79ec8-b0e0-41f3-9214-b47c95201ca6' # Pages
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
