columnSuffix: null
handle: enableWhatsapp
instructions: null
name: 'Add WhatsApp link for phone number?'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
