columnSuffix: null
handle: features
instructions: null
name: Features
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Feature
            -
              - handle
              - feature
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
