columnSuffix: null
handle: fromPrice
instructions: 'Is the listed price a minimum price?'
name: 'From price?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
