columnSuffix: null
handle: sectionHeaderAlignment
instructions: null
name: 'Section header alignment'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - icon
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - top
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
