columnSuffix: null
handle: useParallax
instructions: null
name: 'Use parallax effect on images?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
