defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 09e44c40-286c-4a43-aebc-3a92d572e6fc # Page
handle: legal
maxAuthors: 1
name: Legal
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  67aabd95-1a33-42f9-8870-0d419b6007ab: # Alfred Surgery
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: dbdb75d8-3d93-4b62-bc68-09ed1b3d9554
type: structure
