defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 09e44c40-286c-4a43-aebc-3a92d572e6fc # Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  67aabd95-1a33-42f9-8870-0d419b6007ab: # Renee Boelaars
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{parent.slug}/{slug}'
structure:
  maxLevels: null
  uid: 3fdacd4e-37d1-4648-9c37-fca8cdcd9705
type: structure
