defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: eb702cfa-c688-494d-84ff-bfb378f4f9f0 # Product
handle: products
maxAuthors: 1
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  67aabd95-1a33-42f9-8870-0d419b6007ab: # Alfred Surgery
    enabledByDefault: true
    hasUrls: true
    template: products/_entry.twig
    uriFormat: 'products/{slug}'
structure:
  maxLevels: null
  uid: 2d715dda-b119-4b94-93ce-d999e3ccf18e
type: structure
